//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int idDetalle { get; set; }
        public decimal numFactura { get; set; }
        public decimal idVenta { get; set; }
        public float subTotal { get; set; }
        public string idProducto { get; set; }
        public int cantidad { get; set; }
        public Nullable<bool> despachada { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public Nullable<decimal> precioEntrada { get; set; }
        public Nullable<bool> espcial { get; set; }
    
        public virtual Venta Venta { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
